#!/bin/bash
# =============================================================================
# Paperless-ngx Production Deploy Script for Ubuntu
# Repository: https://github.com/Ayoubkhattab/archive-custom
# =============================================================================
set -e

REPO_URL="https://github.com/Ayoubkhattab/archive-custom.git"
BRANCH="release"
APP_DIR="$HOME/paperless-ngx"
COMPOSE_DIR="$APP_DIR/docker/compose"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'
BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[ OK ]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERR ]${NC} $1"; exit 1; }
step()    { echo -e "\n${BOLD}══ $1 ══${NC}"; }

# =============================================================================
step "1/7  Checking prerequisites"
# =============================================================================

if ! command -v docker &>/dev/null; then
  warn "Docker not found. Installing..."
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER"
  warn "Docker installed. Log out and back in, then re-run this script."
  exit 0
fi
success "Docker: $(docker --version)"

if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 not found. Update Docker to a recent version."
fi
success "Docker Compose: $(docker compose version --short)"

if ! command -v git &>/dev/null; then
  sudo apt-get update -qq && sudo apt-get install -y -qq git
fi
success "Git ready"

# =============================================================================
step "2/7  Clone / Update repository"
# =============================================================================

if [ -d "$APP_DIR/.git" ]; then
  info "Repository exists. Pulling latest..."
  cd "$APP_DIR"
  git fetch origin
  git checkout "$BRANCH"
  git pull origin "$BRANCH"
  success "Repository updated."
else
  info "Cloning $REPO_URL (branch: $BRANCH)..."
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
  success "Cloned to $APP_DIR"
fi

cd "$COMPOSE_DIR"

# =============================================================================
step "3/7  Setup environment (.env.prod)"
# =============================================================================

if [ -f ".env.prod" ]; then
  warn ".env.prod already exists — skipping. Delete it to reconfigure."
else
  HOST_IP=$(hostname -I | awk '{print $1}')
  SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
  DB_PASS=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")

  echo ""
  echo -e "${BOLD}Configure your installation:${NC}"
  echo ""

  # Force reading from terminal even when script is piped (curl | bash)
  exec < /dev/tty

  read -rp "  Admin username [admin]: " ADMIN_USER
  ADMIN_USER=${ADMIN_USER:-admin}

  while true; do
    read -rsp "  Admin password: " ADMIN_PASSWORD; echo ""
    read -rsp "  Confirm password: " ADMIN_PASSWORD2; echo ""
    [ "$ADMIN_PASSWORD" = "$ADMIN_PASSWORD2" ] && break
    warn "Passwords do not match. Try again."
  done

  read -rp "  Machine IP [$HOST_IP]: " CUSTOM_IP
  HOST_IP=${CUSTOM_IP:-$HOST_IP}

  read -rp "  Port [8000]: " APP_PORT
  APP_PORT=${APP_PORT:-8000}

  read -rp "  Ollama endpoint [http://host.docker.internal:11434]: " OLLAMA_EP
  OLLAMA_EP=${OLLAMA_EP:-http://host.docker.internal:11434}

  cat > .env.prod << EOF
# Generated by deploy.sh on $(date)
SECRET_KEY=${SECRET_KEY}
ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
DB_USER=paperless
DB_PASS=${DB_PASS}
DB_NAME=paperless
PAPERLESS_URL=http://${HOST_IP}:${APP_PORT}
PAPERLESS_ALLOWED_HOSTS=localhost,127.0.0.1,${HOST_IP}
PAPERLESS_PORT=${APP_PORT}
TZ=Asia/Riyadh
AI_ENABLED=yes
AI_BACKEND=ollama
AI_MODEL=qwen2:0.5b
AI_ENDPOINT=${OLLAMA_EP}
EOF

  success ".env.prod created."
  info "  URL:   http://${HOST_IP}:${APP_PORT}"
  info "  Admin: ${ADMIN_USER}"
fi

# =============================================================================
step "4/7  Prepare entrypoints"
# =============================================================================

chmod +x entrypoint-prod.sh entrypoint-celery.sh entrypoint-celery-beat.sh
success "Entrypoints are executable."

# =============================================================================
step "5/7  Build Docker image (5-15 min on first run)"
# =============================================================================

info "Building paperless-ngx-custom image..."
docker compose -f docker-compose.prod.yml --env-file .env.prod build
success "Image built."

# =============================================================================
step "6/7  Start services"
# =============================================================================

docker compose -f docker-compose.prod.yml --env-file .env.prod up -d
success "All services started."

# =============================================================================
step "7/7  Health check"
# =============================================================================

info "Waiting for webserver (up to 2 minutes)..."
for i in $(seq 1 24); do
  if docker compose -f docker-compose.prod.yml --env-file .env.prod \
       exec -T webserver curl -sf http://localhost:8000/api/ &>/dev/null; then
    success "Paperless-ngx is responding!"
    break
  fi
  echo -n "."
  sleep 5
done
echo ""

PAPERLESS_URL_VAL=$(grep "^PAPERLESS_URL=" .env.prod | cut -d= -f2)
ADMIN_USER_VAL=$(grep "^ADMIN_USER=" .env.prod | cut -d= -f2)

echo ""
echo -e "${GREEN}${BOLD}============================================${NC}"
echo -e "${GREEN}${BOLD}  Paperless-ngx is ready!${NC}"
echo -e "${GREEN}${BOLD}============================================${NC}"
echo ""
echo -e "  Open:     ${BLUE}${PAPERLESS_URL_VAL}${NC}"
echo -e "  Admin:    ${BLUE}${ADMIN_USER_VAL}${NC}"
echo ""
echo -e "  Logs:     ${YELLOW}docker compose -f $COMPOSE_DIR/docker-compose.prod.yml --env-file $COMPOSE_DIR/.env.prod logs -f${NC}"
echo -e "  Stop:     ${YELLOW}docker compose -f $COMPOSE_DIR/docker-compose.prod.yml --env-file $COMPOSE_DIR/.env.prod down${NC}"
echo -e "  Update:   ${YELLOW}bash $APP_DIR/deploy.sh${NC}"
echo ""
